version: '3.9'
services:
  web:
    container_name: mrshoofer-enterprise
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '127.0.0.1:5000:5000'
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ASPNETCORE_ENVIRONMENT=Production
