name: Build and Push mrshoofer_org Docker Image to Docker Hub

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub with API Token
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mrshoofer_org:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mrshoofer_org:latest

      - name: SSH into server and run Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/mrshoofer_org:latest
            echo "Stopping existing container if running..."
            sudo docker stop mrshoofer_org || true
            echo "Removing existing container if it exists..."
            sudo docker rm mrshoofer_org || true
            echo "Starting new Docker container..."
            sudo docker run -d --name mrshoofer_org -p 5000:8080 ${{ secrets.DOCKER_USERNAME }}/mrshoofer_org:latest
            echo "Deployment complete."
